# Generated by Django 3.0.2 on 2020-01-15 04:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import myHome.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('serviceNumber', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', myHome.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='FireExtinguisherList',
            fields=[
                ('place', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('lastInspectionDate', models.DateField()),
                ('mainInspector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InspectionDateList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspectionDate', models.DateTimeField(auto_now=True)),
                ('fireExtinguisher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myHome.FireExtinguisherList')),
                ('inspector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
