# Generated by Django 3.0.2 on 2020-01-13 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myHome', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='serviceNumber',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
