# Generated by Django 3.0.2 on 2020-01-13 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myHome', '0002_auto_20200113_1421'),
    ]

    operations = [
        migrations.CreateModel(
            name='FireExtinguisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('inspectionDate', models.DateField()),
                ('inspector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myHome.User')),
            ],
        ),
    ]
