# Generated by Django 3.0.2 on 2020-01-29 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myHome', '0002_inspectiondatelist_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='fireextinguisherlist',
            name='image',
            field=models.ImageField(blank=True, upload_to='image'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=5),
        ),
    ]
